-- Fotos sugeridas del lote 1 (docs/fotos/t42-lote-001.csv): solo filas con ficha
-- de producto. Se omite TECLADO ELECTRICO BARBIE (la liga es un listado, no una ficha).
-- Idempotente: volver a correrlo no duplica ni reabre decisiones.
INSERT INTO photo_suggestions (clave, source_url, page_url, fuente, nivel, motivo, lote) VALUES
('7501062023011','https://www.mialegria.com.mx/products/hello-kitty-color-spray-mi-alegria','https://www.mialegria.com.mx/products/hello-kitty-color-spray-mi-alegria','Mi Alegría (fabricante)','muy_alta','Mismo producto (Peluche Hello Kitty Color Spray) en tienda del fabricante','001'),
('7501062025145','https://www.mialegria.com.mx/products/fabrica-de-chocolates-hello-kitty-mi-alegria-crea-y-saborea','https://www.mialegria.com.mx/products/fabrica-de-chocolates-hello-kitty-mi-alegria-crea-y-saborea','Mi Alegría (fabricante)','muy_alta','Mismo producto en tienda del fabricante','001'),
('7501062023004','https://www.mialegria.com.mx/products/squishy-diamantes-hello-kitty-and-friends-mi-alegria','https://www.mialegria.com.mx/products/squishy-diamantes-hello-kitty-and-friends-mi-alegria','Mi Alegría (fabricante)','muy_alta','Mismo producto en tienda del fabricante','001'),
('7501062024032','https://www.mialegria.com.mx/products/arte-en-diamantes-hello-kitty-and-friends-mi-alegria','https://www.mialegria.com.mx/products/arte-en-diamantes-hello-kitty-and-friends-mi-alegria','Mi Alegría (fabricante)','muy_alta','Mismo producto en tienda del fabricante','001'),
('7501062024162','https://www.mialegria.com.mx/products/fabrica-de-gomitas-hello-kitty-mi-alegria','https://www.mialegria.com.mx/products/fabrica-de-gomitas-hello-kitty-mi-alegria','Mi Alegría (fabricante)','muy_alta','Mismo producto en tienda del fabricante','001'),
('7501062002689','https://www.mialegria.com.mx/products/telescopio-20x-40mm-mi-alegria','https://www.mialegria.com.mx/products/telescopio-20x-40mm-mi-alegria','Mi Alegría (fabricante)','muy_alta','Mismo producto y medida en tienda del fabricante','001'),
('7501062019205','https://www.mialegria.com.mx/products/fabrica-de-slime-sirena-mi-alegria','https://www.mialegria.com.mx/products/fabrica-de-slime-sirena-mi-alegria','Mi Alegría (fabricante)','muy_alta','Mismo producto en tienda del fabricante','001'),
('13429927339','https://www.amazon.com.mx/Vamos-Leer-Disney-Nivel-4/dp/B0CCBXPVC6','https://www.amazon.com.mx/Vamos-Leer-Disney-Nivel-4/dp/B0CCBXPVC6','Amazon MX (editorial Dreams Art)','alta','Misma serie y nivel; código no confirmado','001'),
('65541083271','https://www.walmart.com.mx/ip/bolsa-mega-blocks-clasica-azul-80-pcs/00201650500566','https://www.walmart.com.mx/ip/bolsa-mega-blocks-clasica-azul-80-pcs/00201650500566','Walmart MX','alta','Mismo producto; la bolsa cambia de diseño según edición','001'),
('13429927315','https://www.amazon.com.mx/Vamos-Leer-Disney-Nivel-2/dp/B0CCC13G9F','https://www.amazon.com.mx/Vamos-Leer-Disney-Nivel-2/dp/B0CCC13G9F','Amazon MX (editorial Dreams Art)','alta','Misma serie y nivel; código no confirmado','001'),
('13429927322','https://articulo.mercadolibre.com.mx/MLM-2534463844-vamos-a-leer-con-disney-nivel-3-6-7-anos-lightyear-coco-_JM','https://articulo.mercadolibre.com.mx/MLM-2534463844-vamos-a-leer-con-disney-nivel-3-6-7-anos-lightyear-coco-_JM','Mercado Libre (editorial Dreams Art)','alta','Misma serie y nivel; código no confirmado','001'),
('7501062002627','https://www.mialegria.com.mx/products/maletin-de-doctora-rosa','https://www.mialegria.com.mx/products/maletin-de-doctora-rosa','Mi Alegría (fabricante)','alta','Hay varias versiones (maletín rosa, equipo médico); confirmar presentación','001'),
('194735225293','https://www.liverpool.com.mx/tienda/pdp/tablet-crece-conmigo-fisher-price/1149559601','https://www.liverpool.com.mx/tienda/pdp/tablet-crece-conmigo-fisher-price/1149559601','Liverpool','alta','Mismo modelo; hay versión rosa y azul, confirmar color','001'),
('833186002861','https://www.amazon.com.mx/CRAYOLA-Caballete-Pizarr%C3%B3n-Magn%C3%A9tica-Presentaci%C3%B3n/dp/B085BCNFHB','https://www.amazon.com.mx/CRAYOLA-Caballete-Pizarr%C3%B3n-Magn%C3%A9tica-Presentaci%C3%B3n/dp/B085BCNFHB','Amazon MX','alta','Mismo producto (caballete doble 3 en 1); la presentación puede variar','001'),
('833186005329','https://www.amazon.com.mx/Creative-Fun-Caballete-doble-magn%C3%A9ticos/dp/B07PCM1K5S','https://www.amazon.com.mx/Creative-Fun-Caballete-doble-magn%C3%A9ticos/dp/B07PCM1K5S','Amazon MX','alta','Mismo nombre de producto; código no confirmado','001'),
('7501062024148','https://www.mialegria.com.mx/products/mini-color-spray-figura-tie-dye-hello-kitty-mi-alegria','https://www.mialegria.com.mx/products/mini-color-spray-figura-tie-dye-hello-kitty-mi-alegria','Mi Alegría (fabricante)','alta','Probable mismo producto (Mini Color Spray Hello Kitty); nombre no idéntico','001'),
('194735225309','https://www.amazon.com.mx/Fisher-Price-Aprende-Tablet-Aprendizaje-Conmigo/dp/B07DQ32H3Y','https://www.amazon.com.mx/Fisher-Price-Aprende-Tablet-Aprendizaje-Conmigo/dp/B07DQ32H3Y','Amazon MX','alta','Mismo modelo; segundo color (rosa o azul), confirmar','001'),
('13429924970','https://articulo.mercadolibre.com.mx/MLM-2877201204-set-de-4-libros-historias-de-amistad-princesas-disney-_JM','https://articulo.mercadolibre.com.mx/MLM-2877201204-set-de-4-libros-historias-de-amistad-princesas-disney-_JM','Mercado Libre','media','Se encontró set de 4; el de la tienda cuesta 59 y podría ser libro suelto','001'),
('7502010506945','https://www.amazon.com.mx/Apache-Triciclo-Spiderman-Barra-Empuje/dp/B0DGZX6WWS','https://www.amazon.com.mx/Apache-Triciclo-Spiderman-Barra-Empuje/dp/B0DGZX6WWS','Amazon MX','media','Apache tiene varios triciclos Spiderman con barra; modelo exacto no confirmado','001'),
('655244032982','https://www.amazon.com.mx/Novelty-Corp-Rompecabezas-Panor%C3%A1mico-Mandalorian/dp/B09HZ9MWXS','https://www.amazon.com.mx/Novelty-Corp-Rompecabezas-Panor%C3%A1mico-Mandalorian/dp/B09HZ9MWXS','Amazon MX (Novelty)','media','Novelty tiene varios Mandalorian (3 en 1, 500, 1000 piezas); modelo exacto no confirmado','001'),
('887961918717','https://www.mercadolibre.com.mx/barbie-clinica-medica-set-de-muneca-y-30-accesorios/p/MLM19745278','https://www.mercadolibre.com.mx/barbie-clinica-medica-set-de-muneca-y-30-accesorios/p/MLM19745278','Mercado Libre','media','Mattel tiene 2 o más clínicas (HFT68, HKT79); modelo exacto no confirmado','001')
ON CONFLICT (clave, source_url) DO NOTHING;
